#! /bin/bash -ex

# Build script for a trackrdrd el7 RPM
# to be run in the rpmbuild/centos7 docker container.

# Env variables VERSION and RELEASE MUST be set in the docker invocation.
# DIST is set by the rpmbuild/centos7 container.

# The directory mounted to /srv MUST contain these files:
# - this script (named pkg)
# - trackrdrd tarball (trackrdrd-$VERSION.tar.gz)
# - RPM spec file (trackrdrd.spec)
# - systemd unit file (trackrdrd.service)
# - logrotate config for the Kafka plugin (trackrdr-kafka.logrotate)
# - yum repo config for varnish52@packagecloud (varnishcache_varnish5.repo)
#   (see https://packagecloud.io/varnishcache/varnish5/install#manual-rpm)

# At the end of the run, binary, source and debuginfo RPMs are in the
# directory mounted to /srv.

if [ -z $VERSION ]; then
   echo "Env variable VERSION MUST be set"
   exit 1
fi

if [ -z $RELEASE ]; then
   echo "Env variable RELEASE MUST be set"
   exit 1
fi

# delete the peculiar macros from the rpmbuild/centos7 image
rm /home/builder/.rpmmacros

# set up the build environment
cd /home/builder
mkdir -p rpmbuild/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}
cp /srv/trackrdrd.spec rpmbuild/SPECS
cp /srv/trackrdrd-${VERSION}.tar.gz rpmbuild/SOURCES
cp /srv/trackrdrd.service rpmbuild/SOURCES
cp /srv/trackrdr-kafka.logrotate rpmbuild/SOURCES

# install epel7 repo
sudo rpm -Uvh \
     https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm

# install cloudera cdh5 repo (for zookeeper-native)
sudo yum install -y -q https://archive.cloudera.com/cdh5/one-click-install/redhat/7/x86_64/cloudera-cdh-5-0.x86_64.rpm

# set up varnish repo
sudo cp /srv/varnishcache_varnish5.repo /etc/yum.repos.d/

sudo yum -q makecache -y --disablerepo='*' --enablerepo='varnishcache_varnish52'

# build requirements
sudo yum install -y -q varnish-devel pkgconfig make gcc librdkafka-devel \
	zookeeper-native pcre-devel zlib-devel python-docutils

# build RPMs
rpmbuild -ba -D "dist .${DIST}" \
         -D "_version ${VERSION}" \
         -D "_release ${RELEASE}" \
         rpmbuild/SPECS/trackrdrd.spec

sudo cp rpmbuild/RPMS/*/* /srv
sudo cp rpmbuild/SRPMS/* /srv
